language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: UsBOu8ZNcL65GkaEO0kk6ofN2awGqVe7Tmz6U+cNPEIJcNe0haWOGGaXlo3XdmmSB/wX/e3CxRAsgjkqm/mATqqMC2dYAqn3eVm2DLpUKSzxc5jv+t9l6IGubtE8lK+GU3OgnZBQjySsezs/fQL3z2SgnCLWwnf2/Q3bdbFBfNtNCcvVf+CtU5zJpOH6VFcATrcsCI9v2VUNgj9JWzaJ3IGVLKlth9HbrBHZNde8FEEg/s64k7Kd1773G24viv2+iR+AkpWAsfs2JpGKB6kifs4L8cC2W/Uu80Edu2pniZC6vH5o4WyGRkrxENJzha7j0rKlqgqFu+CGYHFVZUaILqfQTkiFjE2ZtiHdIp7tjKNLSxfiVH4Udzg4q3F6qt5ISnPALyiaT17WFZra6/cLHD/9Qa+dS6BQUfP6SxD/DkTpyiwLQjVr6DW0XEHQpsGXmRIBVwoKk+XPN3dyG2dgX4R+ah1+8AUGRtVoQ3lmp4dqW7BYN4RxxbceoVECFglDrYvCD5ihJ/U7E3Dxve703AsfL0lE5riHLuoi+jk8HCriGqUkq/bFJpbQD9GfWbcpiiMUpiXnurwLtQAF91/F6SyfEmEfJXYYH4lU8SzCPnwivAgo/xoVq5aK0D05v/4w3Vdtsh0Vwu7IqivBWhKkxxazebLezhB0HdTqsu4LCmc=
  app:ancient-depths-91113
