language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: fcNbuyNnWS9+YpvsmSGPnzrWIhh5sEPFxsXp0c/9GvtDHdJePcK7+8GA+gXYUP/VS1QvKOulImDRATf5Kp7ELR11WC4mgY4MaQfgSNDrM8TJM1vWl1T/Zu6KV4IrRXw8jb4QwYoFpZfxeHTAGiX6sNnK3V73/LBPgonolB5WfuD8l54Z1ZUdhNGwFCP4BU9bPYnPFgbDyLizM/h+uoH5Z0LG9a4QrtzDKa229CJkQXyYrFj6yRua/13SM/w5ZWeSYFlUi1PS6KwMPFivwd3EYOxRz4uABHItEoh9VDf33vzUiYDPcMndQ1nZoWKWaPOPuubCSFUGEqSyITqg2QpyIhX4YbttZCURxgYHNMcihbEoSqVugCtQkkQn5a4AoBQ9LwYDVRSF5sIe5NwHzF3vSHAbkPd6JfiomxCT+zVBclex8VSxW+l8b+1gx2dSgoZUjUcULBGgPH/CeXXc5rMj/syr/HRCr79LmXrl9pS8sBFRS4kgUQ1Xaed7AOIhzDRhc9furhn5DHQakylBHlaScHgB9fmckp9Rixq4u+0NFNEy6TFaeOojiJtHq5S7GDMPzii68y4dB16MMl3adhpLgWSerxKSM2LiOPzFGWGVegN2ta/xbgJQejHR5G7PvtKbtmvyg0+eN7VYVs7BJe/DexaaDVE61uv7gKTtqhaYVEg=
  app: ancient-depths-91113
